### ISSUE TITLE
Overall contrast is either good, whiter or darker.

### ISSUE THREAD

**Issue by danriches** [6by9/yavta#2]
Hiya 6by9,

This isn't an issue with your code per se but rather a question, did you ever see washed out (whiter) or darker images being captured with your adv7280 eval board? I've tried all I can think of with regards power supply and reset timing etc but still can't fix the issue.

Cheers, Dan

**Comment by 6by9** [comment]
The auto gain control on the ADV728x chips did seem to be a little hit and miss.

Pages 41 & 42 of app note UG637 does say there is a manual gain control option. If your input signal is nicely controlled then that may be an option via registers LG and CG (0x2C-0x30). Both are 12 bit values by the looks of it.
0x2C =0
0x2D = 0xF0 | (chroma_gain >>8)
0x2E = (chroma_gain & 0xFF)
0x2F = 0xF0 | (luma_gain >>8)
0x30 = (luma_gain & 0xFF)
All in page 0 of the register map. Use eg ```adv7180_write(state, 0x002D, value)``` to get the driver to do the page selection and writes atomically.

**Comment by danriches** [comment]
Hiya, I did wonder about the AGC. So those register writes you mention, do I need to adjust the driver and recompile it? If so is there a web page you can point me to to try this out quickly? Sorry to be a pain, your help is very much appreciated. 

Dan

**Comment by 6by9** [comment]
Yes, it's a recompile the driver job.
Because of the paged addressing mode that the chip uses, and the driver caches which page it believes is selected, you can't use the I2C_SLAVE_FORCE ioctl for I2C to override the fact there is a kernel driver loaded on that I2C address.

I'd suggest somewhere in init_device (https://elixir.bootlin.com/linux/latest/source/drivers/media/i2c/adv7180.c#L1264) as
```
		ret = adv7180_write(state, 0x002C, 0x00);
		if (ret < 0)
			goto out_unlock;
		ret = adv7180_write(state, 0x002D, 0xF4);
		if (ret < 0)
			goto out_unlock;
		ret = adv7180_write(state, 0x002E, 0x00);
		if (ret < 0)
			goto out_unlock;
		ret = adv7180_write(state, 0x002F, 0xF4);
		if (ret < 0)
			goto out_unlock;
		ret = adv7180_write(state, 0x0030, 0x00);
		if (ret < 0)
			goto out_unlock;
```

Instructions for recompiling the kernel are at https://www.raspberrypi.org/documentation/linux/kernel/building.md
There is a minor update to the docs if looking at Linux 5.4 - https://github.com/raspberrypi/documentation/pull/1399

**Comment by danriches** [comment]
Outstanding, you're a god send!!

Thanks,  Dan

**Comment by danriches** [comment]
Hmm, this didn't have any effect really. The strange thing is if I issue a "sudo reboot now" and then take a capture after the pi has booted the image is darker, but a full power cycle shows a lighter image with the odd occasional power cycle showing the darker image and a reboot showing an even darker one which is very strange. I've checked power, reset timing, the crystal is good too but is only active when taking a capture which I find odd.

I've also tried with ACE on and off, changed the DC clamp settings and am now at a loss. What would be useful is a dump of the registers at boot after the init process has completed so I can see if there's a difference between a power cycle and soft reboot. If there is a difference I can cater for it but if not then it must be down to the usual suspects of power, reset and timing...

Any pointers on getting a reg dump, not the CSI ones just the usual ones??

Thanks in advance and sorry for being a royal PITA ;)

Dan

**Comment by danriches** [comment]
Please see above comment before I reopened it...

Dan

**Comment by 6by9** [comment]
Totally missed this query before.

Write a small utility to do a load of I2C_RDWR operations to select the register and read it. Do NOT do this in two operations as there is a significant risk that the kernel driver will make it non-atomic and you'll be reading some other register.
Use I2C_SLAVE_FORCE to select your device address even though a kernel driver is active on the address.

Selecting the alternate banks does risk a collision with the kernel driver as it caches the bank that it last selected.

The other alternative would be to add a ```log_status``` function to the driver which dumped out all the settings using a couple of for next loops.
```v4l2-ctl --log-status``` would then print trigger that, and it gets put in the kernel log as well. See any of the other drivers in media/i2c that implement a log_status function - tx9906 looks a reasonably basic example.
