### ISSUE TITLE
if (do_set_dv_timings) -- should it have a return 0 statement?

### ISSUE THREAD

**Issue by FCaroPromel** [6by9/yavta#4]
https://github.com/6by9/yavta/blob/05305e94a83f88b8d8d1847fc30c1aa4a995c0a3/yavta.c#L3141

Raspbian  with Kernel 5.4.
Connected system:  Notebook VGA output --> VGA to HDMI converter -->  Toshiba 358743 Hdmi2Csi2 adapter card -->  RaspberryPi CM3+ on Waveshare Dev board.

Situation:  At boot up,  Yavta detects the input signal, and shows a good image of what is being transmitted.  When the VGA-to-HDMI adapter is disconnected.  The Yavta output screen stops displaying an image, rather it remains stuck on the last frame processed.  While the terminal output messages, stop processing frames.

When I reconnect the VGA-to-HDMI adapter, it fails to reconnect and repeats the following

`QUERY_DV_TIMINGS returned 1280x1024 pixclk 83699480
Framerate is 47
`

What I am not sure of, I've tried a few modification at line #3141 like the following:

> https://github.com/6by9/yavta/blob/05305e94a83f88b8d8d1847fc30c1aa4a995c0a3/yavta.c#L3141

`
> if (do_set_dv_timings) {
>		if( video_set_dv_timings(&dev) < 0) {
>			destroy_mmal(&dev);
>			video_close(&dev);
>			return 0;
>		}
>}
`

What I tried to do, is stop it from trying to detect the `video_set_dv_timings()`,  close the video pipeline and exit.

My attempts did not work so well :-)

What do you recommend? 

Also:
Lines #3147 --> #3154,  

> https://github.com/6by9/yavta/blob/05305e94a83f88b8d8d1847fc30c1aa4a995c0a3/yavta.c#L3147

`{
		struct v4l2_event_subscription sub;

		memset(&sub, 0, sizeof(sub));

		sub.type = V4L2_EVENT_SOURCE_CHANGE;
		ioctl(dev.fd, VIDIOC_SUBSCRIBE_EVENT, &sub);
	}`
are a group of stattements, in braces only.  Was that supposed to be part of an if() statement?

**Comment by FCaroPromel** [comment]
Yikes, the code formatting in my OP comments are terrible. sorry about that.

To update, I added a rather ugly duct-tape solution.
after line  #2638 :: 

> https://github.com/6by9/yavta/blob/05305e94a83f88b8d8d1847fc30c1aa4a995c0a3/yavta.c#L2638

`exit(EXIT_FAILURE);`




This forces Yavta to exit, on the first sign of `ret = ioctl(dev->fd, VIDIOC_S_DV_TIMINGS, &timings);`  errors.

> https://github.com/6by9/yavta/blob/05305e94a83f88b8d8d1847fc30c1aa4a995c0a3/yavta.c#L2636

But I'm afraid that by doing that abruptly, I am forgetting to close important functions.  Must be bad for long-term memory management?

Sorry if I'm asking silly questions, editing C code is certainly not my cup of tea.

**Comment by 6by9** [comment]
Whilst I had looked at adjusting to changes in input format, I wouldn't say it was an overly tested path.

The display side takes frames and keeps the last received frame on display until something comes in to replace it.

Calling exit will abort the application. All kernel drivers are responsible for cleaning up should an application quit without having released any acquired resources.
