### ISSUE TITLE
Mitigating Dropped frames / Lag in MMAL Preview ? Filesystem or other cause? 

### ISSUE THREAD

**Issue by schoolpost** [6by9/yavta#5]
I'm running into some strange behavior that I haven't quite pinned the root cause of. 

I'm working off a slightly modified version of this source ( some MMAL parameter changes. to the render port ) to use this as a base for a Realtime camera application using the HQ camera ( IMX477 ).  think like a video camera, pi boots up with this yavta script running and you get an immediate live view.  

So I've added wiring library to listen to a GPIO pin for the start of the recording, then I allow the "save_video_frame" function to save that buffer data as a series of DNG frames to disk. When the GPIO is pressed again the recording stops and we stop "saving frames" 

For this project, It's also crucial that I be using a external filesystem that plays well with Windows/Mac. So thus far I've tried 2 kernel level drivers for both NTFS ( NTFS3 https://github.com/LGA1150/ntfs3-oot ) and exfat ( exfat-linux https://github.com/arter97/exfat-linux ) these are optimized drivers and do have the speed to deal with the ~80-120MB/s that is being push to them. 

The issue I'm having is even with the appropriate fast hardware ( USB 3.0 SSD ) and appropriate drivers for the filesystems, I'm still getting dropped frames. When I reached the dropped frames I will sometimes get a select() timeout error.

I think this still means there is partial blame to be had with the filesystems because I ran a test earlier with the EXT4 and I recorded somewhere around 68000 frames continuously no dropped frames.  ( maybe I would have gotten one eventually but for all practical purposes It seemed to work, but I simply cant use EXT4 ) 

I'm curious where this is going wrong then? is there any merit to increasing the number of buffers that are spawned in the beginning? ( is there a practical limit? is 32 or 64 or even more buffers going to mitigate the issue? ) there a plethora of other options like "queue-late" and such that I'm not exactly sure should be enabled in this situation. 

and on a second potentially related note, I've also noticed pushing a higher frame rate will cause the MMAL preview to have some considerable latency. There are no dropped frames, but what is happening in the scene vs. what is being displayed on the live preview can have some noticeable ( 500ms+ ) delays that are not always immediate when recording start, but instead will "build latency" as the recording goes along, until it drops a frame and sometimes crashes. 

Is there a way to mitigate this? Can an image frame be dropped entirely from going to live view if it wont make it by a certain amount of time? is the real-time priority option something that can help this? 

I've overclocked the Pi to 2.275ghz among other small tweaks to see if cpu was a bottleneck but I simply can't seem find any other ways to try to solve these issues. 

Thank you, any/all insight is greatly appreciated. I'm probably bending this utility outside of its scope somewhat but what it does is something I couldn't easily replicate so it works as I great base none the less.

**Comment by 6by9** [comment]
As per the ASCII art in the README, the pipeline is 
```
V4L2 -> ISP -+-> preview
	         +-> encode
```
The video_splitter is implemented with ```mmal_buffer_header_replicate```.
Presumably you've tapped off the buffers coming from V4L2 to alsosave the raw frames. Ideally you want to do that in a separate thread to avoid blocking the main thread, but that needs a bit of caution to ensure the buffers are only recycled when finished with.

The preview will display frames at the display frame rate, returning frames early if there are two or more updates within the same frame period, although memory says that is triggered on the next vsync. 
eg
- frame 0 is on the display
- submit 1
- submit 2
- vsync - return 0 & 1, 2 now on display
- submit 3
- vsync - return 2

Now there is a potential delay there as the default is to allocate 3 buffers for the link, so after 2 is submitted the ISP will be stalled waiting for that vsync and buffers coming back. Other than additional memory usage there's no harm in increasing the number of buffers circulating (note it ought to be done on all ports that participate in the buffer header replication. The ISP output and preview input are the critical ones).

The ISP however will never drop a drame, and will hold on to buffers until it can produce the requested output frame. If you stall it then V4L2 will be stalled waiting for new buffers. 

With regard how to avoid stalling the pipe:
- use a separate thread for saving frames as mentioned before
- allocate more buffers from V4L2 and MMAL buffer headers for the input to the ISP to allow more processing latency
- keep a track of how many buffers are queued with the ISP and return them to V4L2 immediately if it has a backlog. (This is going to need a bit more tweaking as currently the code from DQBUF assumes that the next buffer from ```mmal_queue_get(dev->mmal_pool->queue))``` will be in the same order as from V4L2, and that won't be the case).
