### ISSUE TITLE
Strange artifact on the corner of preview

### ISSUE THREAD

**Issue by schoolpost** [6by9/yavta#6]
Using SBGGR12P Bayer pixel format for the preview, coming from HQ Camera. 

I'm getting these weird artifacts in the corner of the frame, they are kind of random and don't always appear. 

![artifact](https://user-images.githubusercontent.com/25234407/105014880-2c04a800-59fe-11eb-8f51-aa692623b965.gif)

**Comment by 6by9** [comment]
This fork of yavta is a hacked together system to test out V4L2 sources, it's not meant to be production code (that would be libcamera).

- Do the raw images show this, or is it only preview? 
- Which variant of Pi? 
- What firmware and kernel? 
- Is this on a vanilla build of yavta from this branch, or with mods? What command line?

**Comment by schoolpost** [comment]
> This fork of yavta is a hacked together system to test out V4L2 sources, it's not meant to be production code (that would be libcamera).
> 
> * Do the raw images show this, or is it only preview?
> * Which variant of Pi?
> * What firmware and kernel?
> * Is this on a vanilla build of yavta from this branch, or with mods? What command line?

1. The first few frame of the saved RAW images will sometimes show this artifact, but subsequent frames will not. 
2. Using a Pi 4B 8GB with an overclock 2.275Ghz
3. **Kernel**: Linux raspberrypi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux  |  **Firmware**: version 194a85abd768c7334bbadc3f1911c10a7d18ed14 (clean) (release) (start_x)
4. This is using a slightly modified version of this branch, mainly some MMAL Parameter changes on the ISP / Render port before they get enabled. As for command line not quite sure what you mean by this? just through the terminal? 

I will mention too that this doesn't happen for the MMAL SBGGR16 pxl format when i do this mapping:
{"SBGGR12", V4L2_PIX_FMT_SBGGR12, 1, MMAL_ENCODING_BAYER_SBGGR16},

The preview image is of course much too dark this way being a 12bit pixel in a 16bit format. 

So might be related an issue with PACKED fmts?

Thanks,

**Comment by schoolpost** [comment]
I can confirm the same artifacts are present on the native version that is in this branch without my modifications. 

Using the HQ Camera. 

`
./yavta -m -n 16 -s 2028x1080 --capture=100000 /dev/video0
`

Would be nice to know if these are coming from v4l2 or a consequence of MMAL?

**Comment by schoolpost** [comment]
Fixed this issue indirectly by switching to a V4L2loopback and doing v4l2copy on that device.

**Comment by 6by9** [comment]
Latest rpi-update has direct support for MMAL_ENCODING_BAYER_SBGGR12 etc through the ISP
https://github.com/Hexxeh/rpi-firmware/blob/master/vc/sdk/opt/vc/include/interface/mmal/mmal_encodings.h#L148

Going through a v4l2loopback makes it sound like it's a race condition in whether the frame has been completed by Unicam before the ISP reads it, or some caching issue with the CPU (hopefully the CPU should never actually touch them).
If the raw shows the effect then that would imply caching. No particular reason why the unpacked formats should have any different behaviour to the packed formats.
